todo_app/urls.py
from django.urls import path
from . import views
from .views import UpdateList



urlpatterns = [
    path("" , views.ListListView.as_view(),name="all_list"),
    path("new" , views.ListCreateView.as_view(),name="list-create"),
    path("list/<int:list_id>/" , views.ItemListView.as_view(),name="list-task"),
    path("list/<int:pk>/edit/" , UpdateList.as_view(),name="list-update"),
    path("list/<int:pk>/delete/" , views.delete_List_view,name="list-delete"),
    path("list/<int:list_id>/task/<int:task_id>" , views.taskView,name="task-details"),
    path("list/<int:list_id>/task/add/",views.CreateTask.as_view(),name="task-add",),
    path("list/<int:list_id>/task/edit/<int:pk>/",views.TaskUpdateView.as_view(),
            name="task-edit"),
    path("list/<int:list_id>/task/delete/<int:pk>/",views.DeleteTask.as_view(),
        name="task-delete"),

]

todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("todo_app.urls"))
]

custom_middleware/models.py
from django.db import models

# Create your models here.

todo_app/models.py
from django.utils import timezone
from django.db import models

# Create your models here.

def one_week_hence():
    return timezone.now() + timezone.timedelta(days=7)

class List(models.Model):
    title=models.CharField(max_length=60)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Task(models.Model):
    list=models.ForeignKey(List,on_delete=models.CASCADE)
    title=models.CharField(max_length=60)
    description=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    due_date=models.DateTimeField(auto_created=True , default=one_week_hence())

    def __str__(self):
        return self.title + " , " + str(self.due_date) 

custom_middleware/views.py
from django.shortcuts import render

# Create your views here.

todo_app/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import(ListView,CreateView,UpdateView,DeleteView)
from .models import List,Task
from django.contrib import messages

# Create your views here.

class ListListView(ListView):
    model=List
    queryset = List.objects.all().order_by("-created_at")
    template_name="todo_app/all_list.html"

class ListCreateView(CreateView):
    model=List
    fields = ["title"]
    success_url = reverse_lazy("list-create")
    def get_context_data(self):
        context = super(ListCreateView, self).get_context_data()
        context["title"] = "Add a new list"
        return context

class UpdateList(ListCreateView,UpdateView):
    # slug_field = 'product_slug'
    # slug_url_list_id = 'product_slug'
    def get_success_url(self):
        return reverse("list-task", args=[self.object.pk])
    def form_valid(self, form):
        messages.success(self.request, "The List was updated successfully.")
        return super(UpdateList,self).form_valid(form)
    
class DeleteListView(DeleteView):
    model:List
    slug_field = 'product_slug'
    template_name="todo_app/list_confirm_delete.html"
    def get_queryset(self):
        return Task.objects.filter(pk=self.kwargs["pk"])
    
    def get_success_url(self):
        return reverse("all_list")
    

def delete_List_view(request, pk):
    # dictionary for initial data with
    # field names as keys
    context ={}
 
    # fetch the object related to passed id
    obj = get_object_or_404(List, pk = pk)
 
 
    if request.method =="POST":
        # delete object
        obj.delete()
        # after deleting redirect to
        # home page
        return HttpResponseRedirect("/")
 
    return render(request, "todo_app/list_confirm_delete.html", context)


class ItemListView(ListView):
    model=Task
    def get_queryset(self):
        return Task.objects.filter(list_id=self.kwargs["list_id"])

    def get_context_data(self):
        context=super().get_context_data()
        context["List"]=List.objects.get(id=self.kwargs["list_id"])
        return context


class CreateTask(CreateView):
    model=Task
    fields=["list",
        "title",
        "description",
        "due_date"]
    # success_url = reverse_lazy("task-add") -->error -->Reverse for 'task-add' with no arguments not found
    

    def get_initial(self):
        initial_data = super(CreateTask, self).get_initial()
        todo_list = List.objects.get(id=self.kwargs["list_id"])
        initial_data["list"] = todo_list
        return initial_data

    def get_context_data(self):
        context = super(CreateTask, self).get_context_data()
        todo_list = List.objects.get(id=self.kwargs["list_id"])
        context["list"] = todo_list
        context["title"] = "Create a new item"
        return context
        
    def get_success_url(self):
        return reverse("list-task", args=[self.object.list_id])



def taskView(request,list_id,task_id):
    task =Task.objects.get(pk=task_id)
    list=List.objects.get(pk=list_id)
    context={
        'task':task,
        'list':list
    }
    return render(request , "todo_app/task.html" , context)

class TaskUpdateView(CreateTask,UpdateView):
    def get_success_url(self):
        return reverse("task-details", args=[self.object.list_id ,self.object.id ])

class DeleteTask(DeleteView):
    model=Task
    slug_field = 'product_slug'
    def get_success_url(self):
        return reverse("list-task", args=[self.object.list_id])

todo_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Simple.css-->
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <title> To-do Lists</title>

</head>

<style>
    /* Custom CSS */
    
     :root {
        --accent: #6e48ad;
        --accent-bg: white;
        --bg: #fff;
        --text: #212121;
        --text-light: #585858;
        --border: #d8dae1;
        --code: #d81b60;
        --preformatted: #444;
    }
    
    article {
        background-color: var(--marked);
        border: 1px solid var(--border);
        border-radius: 5px;
        padding: 1em;
        margin: 1em 0;
    }
    
    h2 {
        text-align: center;
    }
    
    h2,
    h4 {
        margin-top: 0;
    }
    
    hr {
        background: var(--accent);
        border-color: var(--accent);
    }
    
    button,
    a[role="button"] {
        color: white;
        text-decoration: none;
    }
    
    input,
    select,
    textarea {
        width: 100%;
    }
    
    .list1 {
        background-color: #585858;
        padding: 8px;
        margin: 20px;
        font-size: 24px;
        cursor: pointer;
    }
    
    .list1 a {
        color: #f5e2e2;
        text-decoration: none;
    }
    
    li::marker {
        color: black;
    }
    
    .task {
        padding: 20px;
        margin: 15px;
        background-color: antiquewhite;
    }
    
    .task h3 {
        margin-top: 5px;
    }
    
    .task p {
        color: #8d8070;
    }
</style>


<body>

    <header>
        <h1>TODO List</h1>
        <a href="{% url 'all_list' %}">All Lists</a>

    </header>

    <main>
        {% block content %}

        <p>This content will be replaced by different html code for each page.
        </p>
        {% endblock content %}
    </main>
</body>

</html>

todo_app/templates/todo_app/all_list.html
{% extends "base.html" %}{% block content %}
<h2>My List</h2>
<ul>
    {% for list in list_list %}

    <li class="list1">
        <a href="{% url 'list-task' list.pk %}"> {{list.title}}</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'list-create' %}" role="button">
    ✨ Create New Lst
    </a> {% endblock %}

todo_app/templates/todo_app/list_confirm_delete.html
{% extends "base.html" %} {% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }} It will be deleted permanently"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

todo_app/templates/todo_app/list_form.html
{% extends "base.html" %} {% block content %}
<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save Card">
</form>
<a href="{% url 'all_list' %}">
    Cancel
    </a> {% endblock %}

todo_app/templates/todo_app/task.html
 {% extends "base.html" %} {% block content %}
<div class="contaner">
    <h3>{{ task.title | upper}} Task</h3>
    <hr>
    <table>
        <tr>
            <th> List </th>
            <td> {{task.list}}</td>
        </tr>
        <tr>
            <th> Title </th>
            <td> {{task.title}}</td>
        </tr>
        <tr>
            <th> Description </th>
            <td> {{task.description}}</td>
        </tr>
        <tr>
            <th> Due Date </th>
            <td> {{task.due_date}}</td>

        </tr>
    </table>
    <hr>
    <p style="margin-top: 35px;">
        <a href="{% url 'task-edit' list.pk task.pk %}" role="button" style="margin-top: 15px;">
        ✨ Edit the Task
        </a>
        <a href="{% url 'task-delete' list.id  task.pk %}" role="button" style="margin-top: 15px; margin-left: 20px;">
            ❌ Delete the Task
            </a>
    </p>
    <p style="margin-top: 25px;"><a href="{% url 'list-task' list.id %}" style="margin-bottom:60px;">
        Back
        </a></p>
</div>
{% endblock %}

todo_app/templates/todo_app/task_confirm_delete.html
{% extends "base.html" %} {% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

todo_app/templates/todo_app/task_form.html
{% extends "base.html" %} {% block content %}
<h3>{{ title }}</h3>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save Card">
</form>
<a href="{% url 'all_list' %}">
    Cancel
    </a> {% endblock %}

todo_app/templates/todo_app/task_list.html
{% extends "base.html" %} {% block content %}
<h2>{{List | upper}} Tasks </h2>
<ul>
    {% for task in object_list %}
    <div class="task">
        <h3>{{task.title}}</h3>
        <p>Due Date : {{task.due_date}} </p>

        <a href="{% url 'task-details' List.pk  task.pk %}" class="detailsLink"> see Details</a>
    </div>


    {% endfor %}
</ul>
<p style="margin-top: 35px;margin-left: 50px;">
    <a href="{% url 'task-add' List.pk %}" role="button" style="margin-top: 15px;">
    ✨ Add more Tasks
    </a>
</p>
<p style="margin-top: 35px;margin-left: 50px;">
    <a href="{% url 'list-update' List.id  %}" role="button" style="margin-top: 15px;">
    ✨ Edit the List Title
    </a>
    <a href="{% url 'list-delete'  List.pk %}" role="button" style="margin-top: 15px; margin-left: 20px;">
        ❌ Delete the List
        </a>
</p>
<p style="margin-top: 25px;margin-left: 50px;"><a href="{% url 'all_list' %}" style="margin-bottom:60px;">
    Back
    </a></p>
{% endblock %}